#This script tests that Python and Ruby methods/functions both exit at return statements
def add_three(number):
  return number + 3
  number + 27


returned_value = add_three(10)
print(returned_value)
#prints number + 3
